build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with new config properties, you can add these properties here
  # to allow them in the config-validation
  # excludes: 'RuleSet1>Rule1>Property1,RuleSet1>Rule1>Property2'

processors:
  active: true
  exclude:
    - 'DetektProgressListener'
  # - 'AnnotationProcessor' # Rule aggregators from annotations

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  ComplexInterface:
    active: true
    threshold: 10
    includeStaticDeclarations: false
    includeMethodsWithDefaultHandlers: false
  ComplexMethod:
    active: true
    threshold: 15
    ignoreSingleLineCondition: false
    ignoreSimpleWhenEntries: false
  CyclomaticComplexity:
    active: true
    threshold: 15
    ignoreSimpleCases: true
    ignoreSingleLineCondition: false
    ignoreModifierFlags: false
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    threshold: 6
    ignoreDefaultParameters: false
    ignoreDataClasses: true
    ignoreAnnotatedParameter: []
  MethodOverloading:
    active: true
    threshold: 6

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z0-9]*'

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreNumbersInVariableNaming: true
